# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _figuras
else:
    import _figuras

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class figura(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _figuras.delete_figura

# Register figura in _figuras:
_figuras.figura_swigregister(figura)

class rectangulo(figura):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, arg2, arg3):
        _figuras.rectangulo_swiginit(self, _figuras.new_rectangulo(arg2, arg3))

    def area(self):
        return _figuras.rectangulo_area(self)
    __swig_destroy__ = _figuras.delete_rectangulo

# Register rectangulo in _figuras:
_figuras.rectangulo_swigregister(rectangulo)

class cuadrado(rectangulo):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, lado):
        _figuras.cuadrado_swiginit(self, _figuras.new_cuadrado(lado))
    __swig_destroy__ = _figuras.delete_cuadrado

# Register cuadrado in _figuras:
_figuras.cuadrado_swigregister(cuadrado)

class elipse(rectangulo):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, eje1, eje2):
        _figuras.elipse_swiginit(self, _figuras.new_elipse(eje1, eje2))

    def area(self):
        return _figuras.elipse_area(self)
    __swig_destroy__ = _figuras.delete_elipse

# Register elipse in _figuras:
_figuras.elipse_swigregister(elipse)

class circulo(elipse):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, diametro):
        _figuras.circulo_swiginit(self, _figuras.new_circulo(diametro))
    __swig_destroy__ = _figuras.delete_circulo

# Register circulo in _figuras:
_figuras.circulo_swigregister(circulo)



